const ROUTES = {
  AuthScreen: 'AuthScreen',
  SignIn: 'SignInScreen',
  Dashboard: 'Dashboard',
  BarcodeScreen: 'BarcodeScreen',
  ViewBusiness: 'ViewBusiness',
  AuthStack: 'AuthStack',
  MyAccount: 'MyAccount',
  HotList: 'HotList',
  History: 'History',
  EarnShopcoin: 'EarnShopcoin',
  Notification: 'Notification',
  AppLanguage: 'AppLanguage',
  Security: 'Security',
  About: 'About',
  Chat: 'Chat',
  FAQ: 'FAQ',
  ContactUs: 'ContactUs',
  TermCondition: 'TermCondition',
  PrivacyPolicy: 'PrivacyPolicy',
  Send: "Send",
  SendConfirmation: 'SendConfirmation',
  BuyshopCoin: 'BuyShopCoin',
  Discount: "Discount",
  Interest: "Interest",
  AddList: "AddList",
  Home: "Home",
  BuyNow: "BuyNow",
  AddShopDeal: "AddShopDeal",
  AddInterest: "AddInterest",
  Level: "Level",
  Transaction: "Transaction"
};

export default ROUTES;
